### ISSUE TITLE
This is such an amazing library

### ISSUE THREAD

**Issue by liquidvisual** [propjockey/augmented-ui#1]
Holy smokes, what a fantastic idea and brilliant execution - also love the website! Thank you so much for creating this. As a long-time cyberpunk genre enthusiast this definitely scratches an itch. Love it <3

**Comment by James0x57** [comment]
Wow thank you so much! Just checked out your website, it's incredible. If you use augmented-ui somewhere publicly for yourself or a client, please please share the link; I can't wait to see it used by a top-tier professional designer

Seriously means a lot to me. Thank you!!

Closing for correctness sake but cannot state enough how much I appreciate it <3

**Comment by liquidvisual** [comment]
Aw thanks, I'll definitely let you know. I'm inspired now :)
