### ISSUE TITLE
border rendering chatter and clipping on border position change

### ISSUE THREAD

**Issue by davidjost** [propjockey/augmented-ui#20]
Super cool project!

**Expected behavior**
Borders set with `--aug-border-all` always show the line in the specified thickness regardless of position or size.

**Actual behavior**
Some borders are clipped depending on the position calculated by the browser. 

**Example codepen**
https://codepen.io/davidjost/pen/jOjMEQz?editors=0110

**gif**
![Jul-29-2024 10-45-27](https://github.com/user-attachments/assets/d67d65d3-1183-46a5-aca9-f922f85e326f)

**Comment by Debajyati** [comment]
Hey anyone there? I am planning to use this CSS framework to build my portfolio. There's no new release after August, 2020. If this project is not obsolete/abandoned then please respond!

**Comment by JaneOri** [comment]
So so sorry I haven't checked my gh notifications for ages.

Unfortunately, subpixel rounding is a pita with clip-path polygon and the distance between y-axis 100% and 100% - 1px doesn't always render as a full one pixel depending on not only height but location on the page. It's less noticeable with 1.5px border all.

The light effect is sick btw, nice work!

please do re-open or post a new one if you need to. I'll keep an eye one notifications for a week or so
