### ISSUE TITLE
Invalid CSS in #230

### ISSUE THREAD

**Issue by woodsjm** [propjockey/augmented-ui#3]
Love augmented-ui so far. However, I'm using it in a Heroku build (React) and I'm getting a parsing error. Deployment to Netlify and AWS produced the same error.

Line 230:

`--aug-_TOriginX: calc(var(--aug-t-origin-x, calc(var(--aug-_TlJoinRX, 0px) / 2 + var(--aug-_TrJoinLX, 100%) / 2)) + var(--aug-t-offset, 0px));`

Heroku Log:

`...n-x, calc(var(--aug-_TlJoinRX, 0px)/2 + var(--aug-_TrJoinLX, 100%)/2)) + var(--...
----------------------------------------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"`

(For the sake of clarity due to formatting of that code snippet: the log is referencing the second parentheses after the last 2 on line 230).

There are similar lines with deeply nested calc() statements that create the same issue (i.e. 249, 268, 287, 584, 628).

**Comment by James0x57** [comment]
Hey, thank you for checking it out!

Postcss-calc has an error in its parser that's being worked on. You can see details here:
postcss/postcss-calc#77

The "fix" is to disabled postcss's calc parsing until their bug is fixed, per this comment here:
postcss/postcss-calc#77

The package.json diff looks something like this:
![image](https://user-images.githubusercontent.com/7545075/73344469-09570d80-4248-11ea-9fc0-b2e145bde450.png)

If you still run into trouble after that, please let me know.

Thanks again!
//James

**Comment by HZooly** [comment]
Hi @James0x57. 
I get the same issue than @woodsjm with Gatsby build command.
Unfortunately, editing package.json or postcss.config.js didn't changed anything to get Gatsby project work with AugmentedUI.

**Comment by James0x57** [comment]
Hello @HZooly,
Unfortunately anything with baked in dependency on Postcss-calc is going to have this issue until they fix their parsers.

The work around will be to avoid minification of the augmented-ui CSS file until postcss is fixed. I am not familiar with GatsbyJS and wasn't able to find information on customizing that aspect of the build process, but if you have a repo/branch I can check out, and steps to reproduce the issue, I will try to create a work around.

(and please feel free to open a new issue with a link to that project if you have it)

Thank you,
//James

**Comment by HZooly** [comment]
Thanks for your fast answer!

In a Gatsby page, I imported CSS of Augmented UI : `import '../../node_modules/augmented-ui/augmented.css'`
Working well in dev mode.

With `gatsby build`, it doesn't.

`postcss.config.js`
```js
module.exports = () => ({
  plugins: [
    require('tailwindcss'),
    require('cssnano')({
      preset: [
        'default', {
          calc: false
        }
      ]
    })
  ],
})
````

`package.json`
```json
{
  "name": "...",
  "cssnano": {
    "preset": [
      "default",
      {
        "calc": false
      }
    ]
  }
}
```

I tried to override cssnano config with `cssnano.config.js`:
```js
const defaultPreset = require('cssnano-preset-default');

module.exports = defaultPreset({
    calc: false
});
```

But nothing of these actions made build work.

**Comment by galipmedia** [comment]
I am having the same issue, I have tried many things. Did anyone figure this out?

**Comment by James0x57** [comment]
@galipmedia For React you have to copy the `augmented-ui.min.css` file into the `public` folder and include it manually at the top of the `<head>` in your index.html file:
`<link rel="stylesheet" type="text/css" href="./augmented-ui.min.css">`
http://augmented-ui.com/docs/#ecosystem-compatibility

This avoids the buggy minification in the Post CSS ecosystem.

You can read more about using the public folder here: https://create-react-app.dev/docs/using-the-public-folder/

You can read more about the Post CSS bug here (issue has been open for about 1 year): https://github.com/postcss/postcss-calc/issues/77

You can read more about the cssnano bug here (solved, but there hasn't been a release in over a year): https://github.com/cssnano/cssnano/issues/822

**Comment by galipmedia** [comment]
@James0x57 thanks, that's what I ended up doing.

**Comment by D3VL-Jack** [comment]
We managed to overcome this in Gatsby by modifying the WebpackConfig in `onCreateWebpackConfig`

In the root dir, make a file called `gatsby-node.js` with the contents
```javascript
exports.onCreateWebpackConfig = ({ actions, stage, getConfig }) => {
    // only run on build-javascript stage
    if (stage === 'build-javascript') {
        // get current webpack config
        const config = getConfig()

        // find the minimizer
        const minimizer = config.optimization.minimizer.findIndex(_ => _.constructor.name === 'CssMinimizerPlugin')

        // if it doesn't exist, return
        if (minimizer === -1) return console.log('⚠️ - Could not find CSS minimizer')

        // disable the calc option
        config.optimization.minimizer[minimizer].options.minimizerOptions.preset[1].calc = false

        // replace the webpack config with the modified object
        actions.replaceWebpackConfig(config)
    }
}
```

ref: [gatsby/src/utils/webpack.config.js#L743](https://github.com/gatsbyjs/gatsby/blob/bbd62204a1a402efb681a16ead66421f6f017660/packages/gatsby/src/utils/webpack.config.js#L743)

Appologies for digging up an old issue, I hope this helps someone!
