### ISSUE TITLE
Outline/border is cut off on long item in Chrome (Android)

### ISSUE THREAD

**Issue by kyds3k** [propjockey/augmented-ui#4]
I'm having a problem that only shows up in mobile on Chrome - I have a long section (my resume) on my site, and the border cuts off partway down. I can't for the life of me figure out why . . .

My site: https://www.kyds3k.com

**Comment by James0x57** [comment]
Hey @kyds3k thank you so much for checking out augmented-ui - I love the way you used it, looks really cool.

This was a tough one to track down.
I couldn't begin to tell you why but the `fadepulse` animation on your site is involved. If you disable it, the problem stops.

Good news though, it also fixes the problem to put `z-index: 1;` on the ruleset that uses that animation.

![image](https://user-images.githubusercontent.com/7545075/73359471-85f8e480-4266-11ea-9ee9-4cdae6502268.png)
just add the `z-index: 1;` here and it fixes the issue.

Doesn't make a bit of sense buuuut you should be good to go after that.

Please let me know if you need anything else and thank you again!
//James

**Comment by kyds3k** [comment]
@James0x57 Whoops, i just saw this! Thank you! It worked!
