### ISSUE TITLE
Needs inset-bg-size

### ISSUE THREAD

**Issue by Oreolek** [propjockey/augmented-ui#5]
There is `--inset-bg`, but there's no `--inset-bg-size` for the `background-size` property.

**Comment by James0x57** [comment]
Hey, thank you very much for checking out augmented-ui

The value for `--aug-inset-bg` (and `--aug-border-bg`) is a [&lt;background&gt;](https://developer.mozilla.org/en-US/docs/Web/CSS/background) css type. This allows you to set background-size inline (and do multiple layered background images, etc) in a single rule.

Here is more info on how to use the background property in CSS:
https://developer.mozilla.org/en-US/docs/Web/CSS/background

Thanks again!
//James
