### ISSUE TITLE
Stops working when toggling "display: none" on element

### ISSUE THREAD

**Issue by W4G1** [propjockey/augmented-ui#6]
First of all, amazing library! :)

It seems that an augmented element stops working when you toggle `display: none` on the element.

This seems to happen only when `display: none` is added directly in the html element itself inside a style tag.

Like this:
```html
<div augmented-ui="t-clip-x exe" style="display: none">
```

and then remove it:

```html
<div augmented-ui="t-clip-x exe">
```

Any idea what might be causing this?

**Comment by James0x57** [comment]
Hey, thank you for checking it out!

Here is a jsbin I created while trying to reproduce this. It has a button that toggles display:none on 2 augmented elements: https://jsbin.com/dufoxatexu/edit?html,css,output

I also tried it manually in the console and didn't run into any problems.

Could you provide a jsbin or project I can check out + steps to reproduce it?

Will do what I can to help out :)

Thanks again!
//James

**Comment by W4G1** [comment]
Well, it appeared I made a mistake and this wasn't a bug at all..

I was calculating the augs sizes based on another element's width.

So what happened is that when that element's display was set to none, it's width is 0. Which means the augs wouldn't be visible and gives the impression that they aren't working. ¯\\\_(ツ)\_/¯

I'm sorry to bother you.

**Comment by James0x57** [comment]
No bother at all! Thank you very much for using it! 😄
