### ISSUE TITLE
Old CDN link is broken

### ISSUE THREAD

**Issue by jjozwiak** [propjockey/augmented-ui#9]
Hello,

We  have an application that was using the CDN link from the prior version - https://unpkg.com/augmented-ui/augmented.css

This is no longer working. Is there an updated link?

Also, posting here because this may have affected others.

Thank you

**Comment by James0x57** [comment]
Yep, it's in the links at the top of the readme :)
Here you go: https://unpkg.com/augmented-ui@1/augmented.css

Thanks for checking it out!
